-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE CLIENTE (
UltimoNome VARCHAR(50) NOT NULL,
PrimeiroNome VARCHAR(30) NOT NULL,
IDCLIENTE INTEGER PRIMARY KEY,
IDCOR INTEGER, -- CHAVE ESTRANGEIRA
FOREIGN KEY(IDCOR) REFERENCES COR (IDCOR)
);

CREATE TABLE PEDIDO (
ValorTotal DECIMAL(9,2) NOT NULL,
DataPedido DATE NOT NULL,
IDPedido   INTEGER PRIMARY KEY NOT NULL,
IDCLIENTE  INTEGER -- CHAVE ESTRANGEIRA
FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
)

CREATE TABLE ITEM_PEDIDO (
Qtde 		 INTEGER NOT NULL,
ValorParcial DECIMAL(9,2) NOT NULL,
IDItemPedido INTEGER PRIMARY KEY NOT NULL,
IDConfeccao  INTEGER NOT NULL -- CHAVE ESTRANGEIRA
IDPedido 	 INTEGER NOT NULL -- CHAVE ESTRANGEIRA
FOREIGN KEY(IDPedido) REFERENCES PEDIDO (IDPedido),
FOREIGN KEY(IDConfeccao) REFERENCES CONFECÇÃO (IDConfeccao)
)

CREATE TABLE CONFECÇÃO (
Preco 		DECIMAL(9,2) NOT NULL,
Nome 		VARCHAR(50) NOT NULL,
Tamanho 	CHAR(3) NOT NULL,
IDConfeccao INTEGER PRIMARY KEY,
IDCOR 		INTEGER NOT NULL, -- CHAVE ESTRANGEIRA
IDCategoria INTEGER -- CHAVE ESTRANGEIRA
FOREIGN KEY(IDCOR) REFERENCES COR (IDCOR),
FOREIGN KEY(IDCategoria) REFERENCES CATEGORIA (IDCategoria)
);

CREATE TABLE COR (
TAXAEXTRA   DECIMAL(9,2) NOT NULL,
IDCOR 		INTEGER PRIMARY KEY NOT NULL,
NOME 		VARCHAR(30) NOT NULL
FOREIGN KEY(IDCOR) REFERENCES COR (IDCOR)
);

CREATE TABLE CATEGORIA (
IDCategoria 	   INTEGER PRIMARY KEY NOT NULL,
Nome 			   VARCHAR(30) NOT NULL,
PrincipalCategoria INTEGER -- CHAVE ESTRANGEIRA
FOREIGN KEY(IDCategoria) REFERENCES CATEGORIA (IDCategoria)
);


